version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.0.0
  serverless: circleci/serverless-framework@1.0.1

workflows:
  deploy:
    jobs:
      - deploy

jobs:
  deploy:
    executor: serverless/default
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - aws-cli/setup
      - serverless/setup:
          app-name: serverless-framework-orb
          org-name: circleci
      - run:
          name: deploy
          command: serverless deploy --verbose
