version: 2.1

workflows:
  deploy:
    jobs:
      - deploy:
          type: approval

orbs:
  aws-cli: circleci/aws-cli@3.0.0
  serverless: circleci/serverless-framework@1.0.1

jobs:
  deploy:
    executor: serverless/default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - aws-cli/setup
      - serverless/setup:
          app-name: serverless-framework-orb
          org-name: circleci
      - run:
          name: deploy
          command: |
            serverless deploy --verbose
